### ISSUE TITLE
Error:  Unable to load config from environment variables

### ISSUE THREAD

**Issue by cerenodeng** [HubSpot/hubspot-cms-deploy-action#22]
Follow the usage steps and set GitHub secrects but get the error as screenshot below. Thanks.

![error](https://user-images.githubusercontent.com/94158380/201623662-3a51f1e5-ec06-4e7e-aca6-54eda566cd78.png)

**Comment by cathrin-will** [comment]
I have the same issue has someone found a solution?

**Comment by TanyaScales** [comment]
Hi all -- just wondering if you're still having issues? The error message generally indicates to me that the portal ID/PAK is incorrect since is it attempting to run using those two env variables -- if you could send your workflow file contents along as well, that would be helpful to see the configuration is correct.

**Comment by TanyaScales** [comment]
Closing out as stale since there has been no response -- please feel free to reopen or reach out if this is not resolved for you
